language: d

d:
  - dmd
  - gdc
  - ldc

addons:
  postgresql: 9.4

services: postgresql

before_install:
  - dub fetch dscanner

before_script:
  - psql -c 'create database "vibe-test"' -U postgres

script:
  - .test.sh "dbname=vibe-test"

after_success:
  - if [ ${DC} = "dmd" ]; then bash <(curl -s https://codecov.io/bash); fi
